apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - cert-manager
  - weave-gitops
  - traefik
  - cloudflare
  - repositories
  - secrets
  - monitoring/pushprox
  - k3s
  - notifications
