apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mattermost
  namespace: mattermost
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mattermost.local`)
      kind: Rule
      services:
        - name: mattermost
          port: 8065
