apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pushprox-kube-proxy
  namespace: kube-system
spec:
  chart:
    spec:
      chart: rancher-pushprox
      version: 103.0.1
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  interval: 5m
  values:
    metricsPort: 10249
    component: kube-proxy
    serviceMonitor:
      enabled: false
    clients:
      port: 10013
      useLocalhost: true
      https:
        enabled: false
      # Running on all nodes, not just workers
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
