apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-scheduler-service.yaml
  - kube-controller-manager-service.yaml
  - kube-proxy-service.yaml
  - k3s-component-silence-rules.yaml
