apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - namespace.yaml
  - helm-repository.yaml
  - pvc.yaml
  - secret.yaml
  - helm-release.yaml
  - ingressroute.yaml
